name: Flutter Tests

on: push 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Recup code
      uses: actions/checkout@v2 

    - name: Install machine pour build projet flutter 
      uses: subosito/flutter-action@v1 

    - name: Recup Dependencies
      run: flutter pub get 

    - name: Run 
      run: flutter test 
